apiVersion: v1
kind: Secret
metadata:
  name: plateforme-secrets
  namespace: plateforme-electronique
type: Opaque
stringData:
  POSTGRES_USER: plateforme_user
  POSTGRES_PASSWORD: plateforme_pass
  POSTGRES_DB: plateforme_electronique
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_CLIENT_SECRET: platform-secret
  MAIL_USERNAME: yasminegr432@gmail.com
  MAIL_PASSWORD: your-app-password
