apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources : on réutilise tous les manifests existants du dossier k8s
resources:
  - ../k8s

# Surcharge des images Docker locales vers les images Docker Hub yassmineg/*
images:
  - name: plateforme-gateway
    newName: yassmineg/plateforme-gateway
    newTag: latest
  - name: plateforme-frontend
    newName: yassmineg/plateforme-frontend
    newTag: latest
  - name: plateforme-payment
    newName: yassmineg/plateforme-payment
    newTag: latest
  - name: plateforme-invoice
    newName: yassmineg/plateforme-invoice
    newTag: latest
  - name: plateforme-subscription
    newName: yassmineg/plateforme-subscription
    newTag: latest
  - name: plateforme-notification
    newName: yassmineg/plateforme-notification
    newTag: latest
  - name: plateforme-signature
    newName: yassmineg/plateforme-signature
    newTag: latest
  - name: plateforme-eureka
    newName: yassmineg/plateforme-eureka
    newTag: latest
  - name: plateforme-userauth
    newName: yassmineg/plateforme-userauth
    newTag: latest

