apiVersion: v1
kind: Secret
metadata:
  name: plateforme-secrets
stringData:
  POSTGRES_USER: plateforme_user
  POSTGRES_PASSWORD: plateforme_pass
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_DB_PASSWORD: plateforme_pass
  KEYCLOAK_CLIENT_SECRET: platform-secret
  # Gmail: utiliser un "Mot de passe d'application" (Google Compte > Sécurité > Mots de passe des applications)
  MAIL_USERNAME: yasminegr432@gmail.com
  MAIL_PASSWORD: your-app-password
