server:
  port: ${PORT:8085}

spring:
  application:
    name: notification-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgresql}:${DB_PORT:5432}/${DB_NAME:notification_db}
    username: ${DB_USER:plateforme_user}
    password: ${DB_PASSWORD:plateforme_pass}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
