FROM eclipse-temurin:21-jre-alpine
LABEL maintainer="Yesmine GRASSA <yasmineg432@gmail.com>"

WORKDIR /app
EXPOSE 8080
CMD ["sh", "-c", "echo 'signature-service placeholder container'; tail -f /dev/null"]
